### PR TITLE
Refa + Bugfix

### PR DESCRIPTION
**Pull request by njoerd114**
At first, I noted that I forgot to modify the half-budget-notification, other than that it's less code if you combine the two depending on the module configuration. What do you think? I guess it's a "readability vs code-duplication"-discussion

### CODE REVIEW

**Review by JamesWoolfenden — CHANGES_REQUESTED** [review]
Need to fix your merge conflicts, if you run the pre-commit run -a that should fix the readme for you.

**Comment by njoerd114** [comment]
Okay, as a non-python developer on arch-linux not very used to pre-commit-hooks, i first had to install python3.8 + shellcheck... nice thing though, going to try using it more often from now I guess...

**Comment by JamesWoolfenden** [comment]
> Okay, as a non-python developer on arch-linux not very used to pre-commit-hooks, i first had to install python3.8 + shellcheck... nice thing though, going to try using it more often from now I guess...

then hopefully your using checkov as well? - and then my job is done!

**Review by JamesWoolfenden — APPROVED** [review]
LGTM

**Pull request merged**
